services:

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile

    environment:
      PORT_BACKEND: ${PORT_BACKEND}

    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile

    environment:
      PORT_BACKEND: ${PORT_BACKEND}

    ports:
      - "80:80"

    depends_on:
      - backend
