[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tasc"
version = "1.0.0"
requires-python = ">=3.12"
authors = [{ name = "Tobi Adesanya", email = "tobijadesanya@gmail.com" }]
description = "A comprehensive framework for analyzing lexical semantic change across corpora with integrated topic modeling and interactive 3D visualization."
readme = "README.md"
license = { text = "MIT" }
dependencies = ["fastapi[standard]"]

[project.scripts]
tasc = "src.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src"]
